[{:outcome=>:passed, :prediction=>"passed", :number=>0, :info=>"JUnit version 4.7<br/>.<br/>Time: 0.013<br/><br/>OK (1 test)", :time=>[2010, 3, 22, 21, 43, 32]}, {:number=>1, :prediction=>"passed", :outcome=>:failed, :info=>"JUnit version 4.7<br/>.E<br/>Time: 0.007<br/>There was 1 failure:<br/>1) test_hhg(SourceTest)<br/>junit.framework.AssertionFailedError: expected:<41> but was:<42><br/>\tat junit.framework.Assert.fail(Assert.java:47)<br/>\tat junit.framework.Assert.failNotEquals(Assert.java:277)<br/>\tat junit.framework.Assert.assertEquals(Assert.java:64)<br/>\tat junit.framework.Assert.assertEquals(Assert.java:195)<br/>\tat junit.framework.Assert.assertEquals(Assert.java:201)<br/>\tat SourceTest.test_hhg(SourceTest.java:11)<br/>\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br/>\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>\tat java.lang.reflect.Method.invoke(Method.java:616)<br/>\tat junit.framework.TestCase.runTest(TestCase.java:168)<br/>\tat junit.framework.TestCase.runBare(TestCase.java:134)<br/>\tat junit.framework.TestResult$1.protect(TestResult.java:110)<br/>\tat junit.framework.TestResult.runProtected(TestResult.java:128)<br/>\tat junit.framework.TestResult.run(TestResult.java:113)<br/>\tat junit.framework.TestCase.run(TestCase.java:124)<br/>\tat junit.framework.TestSuite.runTest(TestSuite.java:232)<br/>\tat junit.framework.TestSuite.run(TestSuite.java:227)<br/>\tat org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)<br/>\tat org.junit.runners.Suite.runChild(Suite.java:128)<br/>\tat org.junit.runners.Suite.runChild(Suite.java:24)<br/>\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)<br/>\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)<br/>\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)<br/>\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)<br/>\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)<br/>\tat org.junit.runners.ParentRunner.run(ParentRunner.java:236)<br/>\tat org.junit.runner.JUnitCore.run(JUnitCore.java:157)<br/>\tat org.junit.runner.JUnitCore.run(JUnitCore.java:136)<br/>\tat org.junit.runner.JUnitCore.run(JUnitCore.java:117)<br/>\tat org.junit.runner.JUnitCore.runMain(JUnitCore.java:98)<br/>\tat org.junit.runner.JUnitCore.runMainAndExit(JUnitCore.java:53)<br/>\tat org.junit.runner.JUnitCore.main(JUnitCore.java:45)<br/><br/>FAILURES!!!<br/>Tests run: 1,  Failures: 1", :time=>[2010, 3, 22, 21, 43, 42]}]